const fs = require("fs");
const path = require("path");
const { test, expect } = require("@playwright/test");
const {
  addLabHealth,
  attachSmokeData,
  createSmokeReport,
  gotoAndStabilize,
  observePage,
  pushCheck,
  pushWarning
} = require("./smoke-helpers");

const REPORT_PATH = path.join(process.cwd(), "docs", "terminal-guide-audit.txt");

function normalizeCommand(value) {
  return String(value || "")
    .trim()
    .replace(/\s+/g, " ")
    .toLowerCase();
}

function writeGuideAuditReport(audit) {
  const lines = [
    "Terminal Guide Instruction Audit",
    "Generated by: npm run test:smoke",
    "",
    `Summary: ${audit.passed} passed, ${audit.failed} failed, ${audit.total} total terminal exercise steps.`,
    "",
    "This report compares each terminal exercise task with the guide/walkthrough command shown for that task.",
    "PASS means the guide command matches the task command. FAIL means the guide is missing, generic, or points at a different command.",
    ""
  ];

  if (Array.isArray(audit.renderedChecks) && audit.renderedChecks.length) {
    lines.push("Rendered UI Checks");
    audit.renderedChecks.forEach((check) => {
      lines.push(`- ${check.ok ? "PASS" : "FAIL"} ${check.scenarioId}: ${check.details}`);
    });
    lines.push("");
  }

  audit.scenarios.forEach((scenario) => {
    lines.push(`## ${scenario.title} (${scenario.id})`);
    lines.push(`Shell: ${scenario.shell || "unknown"} | Level: ${scenario.level || scenario.difficulty || "unknown"}`);
    scenario.steps.forEach((step) => {
      lines.push("");
      lines.push(`Step ${step.index + 1}: ${step.objective || "Untitled task"}`);
      lines.push(`Result: ${step.ok ? "PASS" : "FAIL"}`);
      lines.push(`Expected task command: ${step.expectedCommand || "[missing]"}`);
      lines.push(`Guide source: ${step.guideSource || "[missing]"}`);
      lines.push(`Guide command: ${step.guideCommand || "[missing]"}`);
      lines.push(`Guide goal: ${step.guideGoal || "[missing]"}`);
      lines.push(`Guide explanation: ${step.guideExplanation || "[missing]"}`);
      if (step.reason) {
        lines.push(`Reason: ${step.reason}`);
      }
    });
    lines.push("");
  });

  fs.mkdirSync(path.dirname(REPORT_PATH), { recursive: true });
  fs.writeFileSync(REPORT_PATH, `${lines.join("\n")}\n`, "utf8");
}

test("Terminal guide audit: walkthrough instructions match each exercise", async ({ page }, testInfo) => {
  test.setTimeout(120000);
  const report = createSmokeReport("Terminal Guide Instruction Audit", "/terminal-coach.html?track=windows&mode=standard&skipIntro=1");
  observePage(page, report);
  await gotoAndStabilize(page, report.url);

  const audit = await page.evaluate(() => {
    const normalize = (value) => String(value || "").trim().replace(/\s+/g, " ");
    const normalizeKey = (value) => normalize(value).toLowerCase();
    const extractBacktickCommands = (value) => {
      const matches = [...String(value || "").matchAll(/`([^`]+)`/g)].map((match) => match[1].trim());
      return matches.flatMap((command) => command.split(/\s+or\s+/i).map((item) => item.trim()).filter(Boolean));
    };
    const isRunnableCommand = (value) => {
      const command = normalize(value);
      return Boolean(command)
        && !/^Use\b/i.test(command)
        && !/^(?:>|#|\(config[^)]*\)#|[A-Za-z0-9_-]+[>#])$/.test(command);
    };
    const commandFromAcceptRule = (rule) => {
      if (!rule) return "";
      if (rule.finalCwd) return `cd ${rule.finalCwd}`;
      if (rule.command) return String(rule.command).trim();
      return "";
    };
    const suggestedCommandForStep = (step = {}) => {
      if (step.demoCommand) return String(step.demoCommand).trim();
      if (Array.isArray(step.walkthrough) && step.walkthrough[0]?.command) {
        return String(step.walkthrough[0].command).trim();
      }
      const hinted = (step.hints || []).flatMap(extractBacktickCommands).find(isRunnableCommand);
      if (hinted) return hinted;
      const commandHint = extractBacktickCommands(step.commandHint)[0] || String(step.commandHint || "").replace(/^Try:\s*/i, "").trim();
      if (isRunnableCommand(commandHint)) return commandHint;
      const acceptCommand = (step.accepts || []).map(commandFromAcceptRule).find(isRunnableCommand);
      if (acceptCommand) return acceptCommand;
      return "";
    };
    const normalizeDemoOutput = (value) => {
      if (Array.isArray(value)) return value.map((item) => String(item || "")).filter(Boolean);
      if (value === null || value === undefined || value === "") return [];
      return [String(value)];
    };
    const normalizeWalkthroughEntries = (entries = []) => (Array.isArray(entries) ? entries : [])
      .map((entry) => {
        if (!entry) return null;
        const command = String(entry.command || entry.demoCommand || "").trim();
        const output = normalizeDemoOutput(entry.output || entry.demoOutput);
        const explanation = String(entry.explanation || entry.demoExplanation || entry.successFeedback || entry.explanationText || "").trim();
        const why = String(entry.why || entry.whyThisMatters || "").trim();
        const objective = String(entry.objective || "").trim();
        const title = String(entry.title || "").trim();
        const goal = String(entry.goal || entry.objective || "").trim();
        if (!command && !explanation && !why && !objective && !title && !goal) return null;
        return { title, goal, command, output, explanation, why, objective };
      })
      .filter(Boolean);
    const guideForStep = (scenario, step) => {
      const stepWalkthrough = normalizeWalkthroughEntries(step.walkthrough);
      if (stepWalkthrough.length) return { source: "step walkthrough", entry: stepWalkthrough[0] };

      const stepDemo = normalizeWalkthroughEntries([{
        command: step.demoCommand,
        output: step.demoOutput,
        explanation: step.demoExplanation,
        whyThisMatters: step.whyThisMatters,
        objective: step.objective
      }]);
      if (stepDemo.length && stepDemo[0].command) return { source: "step demo", entry: stepDemo[0] };

      const command = suggestedCommandForStep(step);
      return {
        source: "generated fallback",
        entry: {
          title: "Guided Task Walkthrough",
          goal: String(step.objective || scenario.objective || "the current task").trim(),
          command,
          explanation: String(step.demoExplanation || step.successFeedback || step.explanation || "This is a safe demo path for the current task.").trim(),
          why: String(step.whyThisMatters || (command ? "This command helps you gather the evidence you need before guessing." : "Use the command reference to pick a command that answers the current task.")).trim()
        }
      };
    };
    const flattenSteps = (scenario) => {
      if (Array.isArray(scenario.stages) && scenario.stages.length) {
        return scenario.stages.flatMap((stage) => stage.steps || []);
      }
      return scenario.steps || [];
    };

    const scenarios = (window.TerminalEngine?.getScenarios?.() || window.ScenarioEngine?.scenarios || [])
      .filter((scenario) => ["cmd", "linux", "cisco"].includes(String(scenario.shell || "").toLowerCase()))
      .filter((scenario) => flattenSteps(scenario).length)
      .map((scenario) => {
        const steps = flattenSteps(scenario).map((step, index) => {
          const expectedCommand = suggestedCommandForStep(step);
          const guide = guideForStep(scenario, step);
          const guideCommand = String(guide.entry.command || "").trim();
          const ok = Boolean(expectedCommand)
            && Boolean(guideCommand)
            && normalizeKey(expectedCommand) === normalizeKey(guideCommand);
          const reason = !expectedCommand
            ? "Could not derive a task command from demo, hints, commandHint, walkthrough, or accept rules."
            : !guideCommand
              ? "Guide does not provide a command."
              : ok
                ? ""
                : `Guide command "${guideCommand}" does not match task command "${expectedCommand}".`;
          return {
            index,
            objective: step.objective || "",
            expectedCommand,
            guideSource: guide.source,
            guideCommand,
            guideGoal: guide.entry.goal || guide.entry.objective || "",
            guideExplanation: guide.entry.explanation || guide.entry.why || "",
            ok,
            reason
          };
        });
        return {
          id: scenario.id,
          title: scenario.title,
          shell: scenario.shell,
          level: scenario.level || scenario.difficulty || "",
          steps
        };
      });

    const flatSteps = scenarios.flatMap((scenario) => scenario.steps);
    return {
      total: flatSteps.length,
      passed: flatSteps.filter((step) => step.ok).length,
      failed: flatSteps.filter((step) => !step.ok).length,
      renderedChecks: [],
      scenarios
    };
  });

  await page.evaluate(() => localStorage.setItem("networkingGame.explainerSeen.ping", "1"));
  await page.evaluate(() => window.TerminalEngine?.loadScenarioById?.("win-ping-fileserver"));
  await page.waitForTimeout(250);
  if (await page.locator("#ticketBriefingStartBtn").isVisible().catch(() => false)) {
    await page.locator("#ticketBriefingStartBtn").click();
    await page.waitForTimeout(150);
  }
  if (await page.locator("#commandExplainerDoneBtn").isVisible().catch(() => false)) {
    await page.locator("#commandExplainerDoneBtn").click();
    await page.waitForTimeout(150);
  }
  await page.locator("#watchWalkthroughBtn").click();
  await expect(page.locator("#walkthroughCard")).toBeVisible();
  const renderedCommand = ((await page.locator("#walkthroughCommand").textContent()) || "").trim();
  const renderedOutput = ((await page.locator("#walkthroughOutput").textContent()) || "").trim();
  const renderedOk = /ping\s+(?:fileserver|192\.168\.56\.20)/i.test(renderedCommand)
    && /Reply from 192\.168\.56\.20/i.test(renderedOutput)
    && !/^C:\\Users\\student>$/.test(renderedCommand)
    && !/No output shown/i.test(renderedOutput);
  audit.renderedChecks.push({
    scenarioId: "win-ping-fileserver",
    ok: renderedOk,
    details: `command="${renderedCommand}" output="${renderedOutput.replace(/\s+/g, " ").slice(0, 120)}"`
  });
  await page.locator("#walkthroughCloseBtn").click();
  await expect(page.locator("#walkthroughCard")).toBeHidden();

  const failures = audit.scenarios.flatMap((scenario) => (
    scenario.steps
      .filter((step) => !step.ok)
      .map((step) => `${scenario.id} step ${step.index + 1}: ${step.reason}`)
  ));
  const renderedFailures = audit.renderedChecks
    .filter((check) => !check.ok)
    .map((check) => `${check.scenarioId}: rendered guide did not show the expected command/output (${check.details})`);
  const allFailures = failures.concat(renderedFailures);

  writeGuideAuditReport(audit);

  addLabHealth(report, {
    pagesTested: ["terminal guide audit"],
    acceptedVariations: [`${audit.passed}/${audit.total} guide instructions matched`],
    rejectedReasonableAlternatives: allFailures.slice(0, 25)
  });
  pushCheck(report, "terminal guide audit report written", fs.existsSync(REPORT_PATH), REPORT_PATH);
  pushCheck(report, "all terminal guide commands match exercise commands", allFailures.length === 0, allFailures.slice(0, 20).join(" | "));
  allFailures.slice(0, 25).forEach((failure) => pushWarning(report, failure));

  await testInfo.attach("terminal-guide-audit.txt", {
    path: REPORT_PATH,
    contentType: "text/plain"
  });
  await attachSmokeData(testInfo, report);

  expect(allFailures, allFailures.slice(0, 20).join("\n")).toEqual([]);
});
